server:
  port: 8282

spring:
  datasource:
    platform: mysql
    initialization-mode: never
    sql-script-encoding: UTF-8
    url: jdbc:mysql://127.0.0.1:3306/springsecurity?serverTimezone=UTC&autoReconnect=true
    username: connie2
    password: connie2!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mustache:
    prefix: classpath:/templates/
    suffix: .html
logging.level:
  org.hibernate.SQL: debug